### ISSUE TITLE
Use native Promise

### ISSUE THREAD

**Issue by johnbwoodruff** [gshigeto/clocky-api#1]
Since we can run this on node 6.9+ we can use native Promises instead of the `q` library. (For example on [Line 42](https://github.com/gshigeto/clocky-api/blob/master/google.js#L42) of `google.js`)

**Comment by johnbwoodruff** [comment]
@gshigeto you should go for it! :D

**Comment by gshigeto** [comment]
@jbw91 thanks for bringing this one up!
